services:
  db:
    image: postgres:latest
    container_name: zytho_postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: zythologue-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
  
  api:
    build:
      context: ./
    container_name: api_zythologue
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  db-data: