name: Build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/zythologue-api .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/zythologue-api
      
      - name: Trigger Render Deployment
        run: |
          curl -X POST https://api.render.com/deploy/srv-cunkojq3esus73cjpok0?key=0pIbQn88AzM